config/routes.rb
SampleApp::Application.routes.draw do
  get "participations/new"

	resources :users do
		member do
			get :following, :followers, :info, :deletefavourite, :follow, :unfollow, :participations, :activities
		end
	end

	resources :sessions, only: [:new, :create, :destroy]

	resources :posts, only: [:create, :destroy]
	resources :post_comments, only: [:create, :destroy]

	resources :followings, only: [:create, :destroy]

	resources :activities do
		member do
			get :removeFacility, :join, :cancel, :comment
		end
	end

	resources :participations

	resources :facilities do
    	member do
     		 get :evaluate, :addToActivity, :set, :activities
		end
	end

	resources :activity_comments, only: [:create, :destroy]

	resources :activity_facilities, only: [:create, :destroy]

	resources :evaluations, only: [:create, :destroy]

	root to: 'static_pages#home'

	match '/find_activity', to: 'activities#find', via: :get
	match '/find_activities', to: 'activities#find_activities', via: :get

	match '/find_users', to: 'users#find_users', via: :get	

	match '/create_activity', to: 'activities#new'
	match '/my_activities', to: 'activities#my'

	match '/find_facilities', to: 'facilities#find_facilities', via: :get

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/my_participations', to: 'activities#participations'

	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		if(signed_in?)
			@posts = Post.joins("inner join followings on followings.followed_id = posts.target_id").where("follower_id = ? or target_id = ?", current_user.id, current_user.id).uniq.order("created_at asc").paginate(page: params[:page])
			@activities = Activity.joins(:participations).where("participations.user_id = ? AND beg_date > ?", current_user.id, Date.today.to_date).order("beg_date asc").limit(10)
			@my_activities = Activity.where("user_id = ? AND beg_date > ?", current_user.id, Date.today.to_date).order("beg_date asc").limit(8)
		end
	end

	def about
	end

	def sign_in
	end

	def wall
		if signed_in?
			@activity = Activity.where("user_id = ?", current_user.id).paginate(page: params[:page])
		end
	end

	def create_activity
		if signed_in?
			@activity  = current_user.activities.build
			@feed_items = current_user.feed.paginate(page: params[:page])
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/....html.erb
<h1>StaticPages#...</h1>
<p>Find me in app/views/static_pages/....html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h3>About Activity Finder</h3>
<hr>

<p>
	Activity finder is the web page which helps people to find sport activities according their interest and choosen location. It also includes many sport facilities which can be evaluated and add to 	activities.	
</p>

<p>
	This page was created as a help for people who would like to practise any type of sport, but they do not have appropriate sport partners. You can find there also sport facilities for your	activities, add to someone who practising sport in your favourite one or just find out any information about facility in chosen location.
</p>

<hr>

<h4>What can I do without registration?</h4>

<p>
	You can find sport activities according your interest and look at information about this activity. At the home page you choose location and type of activity. Then click "Find activity" and choose from activities in our database. Click at one of them to see more information about the activity.
</p>

<p>
	If you want to find any sport facility you can choose location and activity type of the facility and click "Find facility". Then just choose and look at the information about choosen one.
</p>

<hr>

<h4>Why registration?</h4>

<p>
	Registration will open new functionality for you:
</p>

<p>
	<b>Home page</b><br>
	Home page give you possibility to see and control everything important for you. On the top there are buttons represent most important functions for you.<br>
	On the left side under profile photo, there is the list which includes activities created by you. Right side includes your future activity participaions.<br>
	Central part of home page is your post feed. There are your posts and posts of users you follow with comments. You can add new post or comment existing one. Among posts are also new activities which was created.  
</p>

<p>
	<b>Create activty</b><br>
	Creating new activity is really easy. Just choose Create Activity, fill the fields, click Create and wait for new participants.
</p>
	
<p>
	<b>Users' profiles</b><br>
	Every user of Activity Finder has created own profile page which includes his/her posts. Using tabs you can select among general, profile info, created activities, participations, user's following and followers.
</p>

<p>
	<b>My Activities</b><br>
	After choosing My Activities you can see all activities created by you ordered by date of begin.
</p>

<p>
	<b>My Participations</b><br>
	After choosing My Participations you can see all activities you participate ordered by date of begin.
</p>

<p>
	<b>Join to and comment activities</b><br>
	Click Join activity to show your interest to participate this activity and add the comment.
</p>

<p>
	<b>Evaluate facilities</b><br>
	Do you have any exparience with facility in our database? Add a evaluation of this facility to help other users.
</p>

<hr>

<center>
	<p>
		Not enough information? You want to help us? Do you have any idea to make Activity Finder better? Did you find any bug?
	</p>

	<%= link_to contact_path, :class => 'btn btn-medium'  do %>
		<i class="icon-black icon-globe"></i> Contact us
	<% end %>
</center>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="row">

	<div class="span8 offset2">

		<div class="well">

			<h3>Contact</h3>
			<hr>

			<p>
				<b>Author:</b> Jozef Zatko
			</p>

			<p>
				<b>Email:</b> zatko7071@gmail.com
			</p>

			<p>
				<b>Created:</b> march-june 2013 --> <b>Research seminar</b> project (<a href="http://www.fiit.stuba.sk/">FIIT STU</a>)
			</p>

		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>

	<div class="btn-group">

		<%= link_to my_activities_path, :class => 'btn'  do %>
			<i class="icon-star icon-black"></i> My activities
		<% end %>

		<%= link_to my_participations_path, :class => 'btn'  do %>
			<i class="icon-tags icon-black"></i> My participations
		<% end %>

		<%= link_to create_activity_path, :class => 'btn'  do %>
			<i class="icon-plus icon-black"></i> Create activity
		<% end %>

		<%= link_to find_activities_path, :class => 'btn'  do %>
			<i class="icon-search icon-black"></i> Find activities
		<% end %>

		<%= link_to facilities_path, :class => 'btn'  do %>
			<i class="icon-search icon-black"></i> Find facilities
		<% end %>

		<%= link_to users_path, :class => 'btn'  do %>
			<i class="icon-search icon-black"></i> Find users
		<% end %>

		<%= link_to following_user_path(current_user), :class => 'btn'  do %>
			<i class="icon-eye-open icon-black"></i> Who I follow
		<% end %>

		<br><br>

	</div>
	

	<div class="row">
		<aside class="span3">

			<section>
				<%= render 'shared/user_info' %>
			</section>


			<section>

				<h4>Created by me:</h4>
		
				<% @my_activities.each do |i| %>

					<a href="<%= activity_path(i) %>">
						<font color="black">
							<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

								<%= i.beg_date %> (<%= time_ago_in_words(i.beg_date) %>)<br>
								<%= i.getParticipantCount %> joined people<br>
								<%= i.getType %><br>
								<%= i.getLocation %>

							</div>
						</font>
				<% end %>

			</section>


		</aside>



		<div class="span6">

			<%= form_for Post.new do |f| %>

				<%= render 'shared/error_messages', object: f.object %>
				
				<div class="field">
					<%= f.text_area :content, placeholder: "Write a post..." %>
					<%= f.hidden_field :target_id, :value => current_user.id %>
				</div>

				<%= f.submit " Add post ", class: "btn btn-small btn-primary" %>

			<% end %>

			<hr>

			<ol class="posts">
				<%= render @posts %>
			</ol>
			<%= will_paginate @posts %>

		</div>


		<aside class="span3">
			
			<section>
					
				<h4>My future participations:</h4>
						
				<% @activities.each do |i| %>

					<a href="<%= activity_path(i) %>">

						<font color="black">
							<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

								<%= time_ago_in_words(i.beg_date) %> (<%= i.beg_date %>)<br>
								<%= i.getParticipantCount %> joined people<br>
								<%= i.getType %><br>
								<%= i.getLocation %>

							</div>
						</font>

					</a>

				<% end %>
						
			</section>

		</aside>

  	</div>


<% else %>

	<div class="row">	

		<%= image_tag("/images/logo.png") %>
		<hr>

		<aside class="span4">

			<div class="well">
				<center>

					<%= link_to new_user_path, :class => 'btn btn-large'  do %>
						<i class="icon-black icon-list-alt"></i> <big>Sign up now for free</big>
					<% end %>

					<br><br>
					<big><%= link_to "Why should I sign up?", new_user_path %></big>

				</center>
			</div>
				

			<div class="well">

				<h4>About Activity finder:</h4>

				Activity finder is the web page which helps people to find sport activities according their interest and chosen location. It includes many sport facilities which can be evaluated and add to activities...
					
				Look <%= link_to "there", about_path %> for more information.

			</div>

		</aside>


		<div class="span8">


			<div style="float: right;">
				<%= link_to about_path, :class => 'btn btn-medium'  do %>
					<i class="icon-black icon-question-sign"></i> <big>What is Activity Finder?</big>
				<% end %>
			</div>
			<br>
				

			<h3>Find sport activity</h3>
				
			<%= form_tag '/find_activities', method: :get do %>

				<div class="well">

					<div style="width: 100%;">
						
						<div style="float: left; width: 39%">
							<%= label_tag :location_id, 'Location' %>
						</div>


						<div style="float: left; width: 39%">
							<%= label_tag :activity_type_id, 'Activity type' %>
						</div>

					</div>
					<div style="clear:both"></div>


					<div style="width: 100%;">
						
						<div style="float: left; width: 39%">
							<%= collection_select(:location_id, nil , Location.order('name'), :id, :name) %>
						</div>


						<div style="float: left; width: 39%">
							<%= collection_select(:activity_type_id, nil , ActivityType.all, :id, :name,) %>
						</div>
					
						<div style="float: right;">
							<%= submit_tag 'Find activity', class: "btn btn-large btn-primary" %>
						</div>

					</div>
					<div style="clear:both"></div>

				</div>


			<% end %>

			<hr>


			<h3>Find sport facility</h3>

			<%= form_tag '/find_facilities', method: :get do %>

				<div class="well">

					<div style="width: 100%;">
						
						<div style="float: left; width: 39%">
							<%= label_tag :location_id, 'Location' %>
						</div>


						<div style="float: left; width: 39%">
							<%= label_tag :activity_type_id, 'Activity type' %>
						</div>

					</div>
					<div style="clear:both"></div>


					<div style="width: 100%;">
						
						<div style="float: left; width: 39%">
							<%= collection_select(:location_id, nil , Location.order('name'), :id, :name) %>
						</div>

						<div style="float: left; width: 39%">
							<%= collection_select(:activity_type_id, nil , ActivityType.all, :id, :name,) %>
						</div>
					
						<div style="float: right;">
							<%= submit_tag 'Find facility', class: "btn btn-large btn-primary" %>
						</div>

					</div>
					<div style="clear:both"></div>

				</div>


			<% end %>

		</div>

  	</div>
	
<% end %> 

  