config/routes.rb
SampleApp::Application.routes.draw do
  get "participations/new"

	resources :users do
		member do
			get :following, :followers, :info, :deletefavourite, :follow, :unfollow, :participations, :activities
		end
	end

	resources :sessions, only: [:new, :create, :destroy]

	resources :posts, only: [:create, :destroy]
	resources :post_comments, only: [:create, :destroy]

	resources :followings, only: [:create, :destroy]

	resources :activities do
		member do
			get :removeFacility, :join, :cancel, :comment
		end
	end

	resources :participations

	resources :facilities do
    	member do
     		 get :evaluate, :addToActivity, :set, :activities
		end
	end

	resources :activity_comments, only: [:create, :destroy]

	resources :activity_facilities, only: [:create, :destroy]

	resources :evaluations, only: [:create, :destroy]

	root to: 'static_pages#home'

	match '/find_activity', to: 'activities#find', via: :get
	match '/find_activities', to: 'activities#find_activities', via: :get

	match '/find_users', to: 'users#find_users', via: :get	

	match '/create_activity', to: 'activities#new'
	match '/my_activities', to: 'activities#my'

	match '/find_facilities', to: 'facilities#find_facilities', via: :get

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/my_participations', to: 'activities#participations'

	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
	attr_accessible :id, :name, :email, :password, :password_confirmation, :birth_date, :contact, :location_id
	has_secure_password

	has_many :activities, dependent: :destroy
	has_many :user_activities, dependent: :destroy  
	has_many :evaluations
	has_many :participations, dependent: :destroy
	has_many :activity_comments, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :followings, dependent: :destroy

	has_many :reverse_followings, class_name:  "Following", dependent:   :destroy
	has_many :followers, through: :reverse_followings, source: :follower

	has_many :followed_users, through: :followings, source: :followed

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    Activity.where("user_id = ?", id)
  end

	def myActivities
		@x = UserActivity.where("user_id = ?", id)
	end

	def getActivities
		@act = Activity.where("user_id = ?", id)
	end

	def getActivityCount
		@count = Activity.where("user_id = ?", id).count
	end
	
	def getType(type)
		@type = ActivityType.find(type)
	end

	def getLocation
		@loc = Location.find(location_id).name
	end

	def age		
		if birth_date == nil
			"no value"
		else
  			now = Time.now.utc.to_date
  			now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
		end
	end

	def getParticipatingActivities
		@participations = Participation.where("user_id = ?", id).activity_id
		@activities = Activities.find(@participations)
	end

	def getFollowedCount
		@count = Following.where("follower_id = ?", id).count
	end

	def getFollowersCount
		@count = Following.where("followed_id = ?", id).count
	end

	def followingsCount(user)
		@count = Following.where("follower_id = ? AND followed_id = ?", id, user.id).count
	end

	def getFollowings(user)
		@followings = Following.where("follower_id = ? AND followed_id = ?", id, user.id)
	end

	def following?(other_user, user)
		Following.where("followed_id = ? AND follower_id = ?", other_user.id, user.id)
	end

	def follow!(other_user)
		followings.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		followings.find_by_followed_id(other_user.id).destroy
	end

	private

    def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :addfavourite, :show, :info, :follow, :unfollow, :followers, :following]
	before_filter :correct_user,   only: [:edit, :update, :addfavourite]
	before_filter :admin_user,     only: :destroy

	def show
		@user = User.find(params[:id])
		@favourites = UserActivity.where("user_id = ?", @user.id)
		@posts = Post.where("target_id = ?", @user.id).limit(30)
		@activities = Activity.joins(:participations).where("participations.user_id = ? AND beg_date > ?", @user.id, Date.today.to_date).order("beg_date asc").limit(5)
		@my_activities = Activity.where("user_id = ? AND beg_date > ?", @user.id, Date.today.to_date).order("beg_date asc").limit(5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:success] = "Welcome to the Activity Finder. Feel free to use it.\n"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def addfavourite
	end

	def update
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end

	def index
		@recommended = User.where("location_id = ? AND id != ?", current_user.location_id, current_user.id)
		@recommended = @recommended.shuffle[0,10]
	end

	def info
		@user = User.find(params[:id])
	end

	def follow
		@user = User.find(params[:id])
		@following = Following.new
		@following.follower_id = current_user.id
		@following.followed_id = @user.id
		@following.save!

		redirect_to @user
	end

	def unfollow
		@user = User.find(params[:id])
		@following = Following.where("follower_id = ? and followed_id = ?", current_user.id, @user.id).destroy_all

		redirect_to @user
	end

	def followers
		@user = User.find(params[:id])
		@followers = User.joins("inner join followings on followings.follower_id = users.id").where("followed_id = ?", @user.id)
	end

	def following
		@user = User.find(params[:id])
		@followings = User.joins("inner join followings on followings.followed_id = users.id").where("follower_id = ?", @user.id)
	end

	def find_users
		@users = User.where("location_id = ? AND name ilike ?", params[:location_id], '%' + params[:name].to_s + '%')

		@location = params[:location_id]
		@text = params[:name]
	end

	def participations
		@user = User.find(params[:id])
		@participations = Activity.joins(:participations).where("participations.user_id = ? AND beg_date > ?", @user.id, Date.today.to_date).order("beg_date asc")
	end

	def activities
		@user = User.find(params[:id])
		@activities = Activity.where("user_id = ? AND beg_date > ?", @user.id, Date.today.to_date).order("beg_date asc")
	end

	def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
	end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.followings.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user,current_user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.getFollowings(@user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<a href="<%= user_path(user) %>">

	<font color="black">
		<div class="well" style="width:96%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

			<big><b><%= user.name %></b> (<%= user.getLocation %>)</big>


			<div style="width: 100%;">
					<div style="float:left; width: 20%">
						<b>Age:</b> <br> <b>Contact:</b>
					</div>


					<div style="float:left;">
						<%= user.age %> <br> <%= user.contact %><% if user.contact == nil%>no value<% end %>
					</div>

				</div>
				<div style="clear:both"></div>


			 

		</div>
	</font>
</a>

app/views/users/activities.html.erb
<% provide(:title, @user.name + "'s activities") %>

<% if signed_in? %>

	<ul class="nav nav-tabs">

		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/activities">Created activities</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/participations">Participations</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>

	</ul>

	<div class="row">
		<%= render @activities %>
	</div>	

<% end %>

app/views/users/addfavourite.html.erb
<h3>haha</h3>

app/views/users/followers.html.erb
<% provide(:title, @user.name + "'s followers") %>

<% if @user != current_user %>

	<ul class="nav nav-tabs">
		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/activities">Created activities</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/participations">Participations</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<div class="well">
						Favourite activities:
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<%= @user.getType(i.activity_type_id).name %>
							</dd>
						<% end %>
		 			 </div>
				</section>

			</aside>

			<div class="span9">

				<div class="well">

					<% @followers.each do |i| %>
						<dd>
							<%= link_to i.name, i %>
						</dd>
					<% end %>

				</div>

			</div>

	  	</div>

<% else %>

	<ul class="nav nav-tabs">
		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<div class="well">
						Favourite activities:
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<%= @user.getType(i.activity_type_id).name %><button class="close">&times;</button>
							</dd>
						<% end %>

						<br><%= link_to "Add favourite activity", info_user_path, :method => "get" %>
		 			 </div>
					<hr>
				</section>

			</aside>

			<div class="span9">
			
				<div class="well">

					<% @followers.each do |i| %>
						<dd>
							<%= link_to i.name, i %>
						</dd>
					<% end %>

				</div>

			</div>

	  	</div>	
<% end %>

app/views/users/following.html.erb
<% provide(:title, @user.name + "'s followings") %>

<% if @user != current_user %>

	<ul class="nav nav-tabs">
		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/activities">Created activities</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/participations">Participations</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<div class="well">
						Favourite activities:
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<%= @user.getType(i.activity_type_id).name %>
							</dd>
						<% end %>
		 			 </div>
				</section>

			</aside>

			<div class="span9">

				<div class="well">

					<% @followings.each do |i| %>
						<dd>
							<%= link_to i.name, i %>
						</dd>
					<% end %>

				</div>

			</div>

	  	</div>

<% else %>

	<ul class="nav nav-tabs">
		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<div class="well">
						Favourite activities:
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<%= @user.getType(i.activity_type_id).name %><button class="close">&times;</button>
							</dd>
						<% end %>

						<br><%= link_to "Add favourite activity", info_user_path, :method => "get" %>
		 			 </div>
					<hr>
				</section>

			</aside>

			<div class="span9">
			
				<div class="well">

					<% @followings.each do |i| %>
						<dd>
							<%= link_to i.name, i %>
						</dd>
					<% end %>

				</div>

			</div>


	  	</div>	
<% end %>

app/views/users/info.html.erb
<% provide(:title, @user.name + "'s info") %>

<% if @user != current_user %>

	<ul class="nav nav-tabs">
		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/activities">Created activities</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/participations">Participations</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<div class="well">
						Favourite activities:
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<%= @user.getType(i.activity_type_id).name %>
							</dd>
						<% end %>
		 			 </div>
				</section>

			</aside>

			<div class="span9">

				<div class="well">
					<p><b>Name: </b><%= @user.name %></p>
					<p><b>Age: </b><%= @user.age %></p>
					<p><b>Contact: </b><%= @user.contact %></p>
					<p><b>Location: </b><%= @user.getLocation %></p>
				</div>

			</div>

	  	</div>

<% else %>

	<ul class="nav nav-tabs">
		<li>
			<a href="../<%= @user.id %>">General</a>
		</li>

		<li class="active">
			<a href="../<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="../<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<div class="well">
						Favourite activities:
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<%= @user.getType(i.activity_type_id).name %><button class="close">&times;</button>
							</dd>
						<% end %>

						<br><%= link_to "Add favourite activity", info_user_path, :method => "get" %>
		 			 </div>
					<hr>
				</section>

			</aside>

			<div class="span9">

				<div style="float:right;">
					<%= link_to edit_user_path(current_user), :class => 'btn'  do %>
						<i class="icon-wrench icon-black"></i> Acount settings
					<% end %>
				</div>

				<br><br>
			
				<div class="well">
					<p><b>Name: </b><%= @user.name %></p>
					<p><b>Birth date: </b><%= @user.birth_date %></p>
					<p><b>Contact: </b><%= @user.contact %></p>
					<p><b>Location: </b><%= @user.getLocation %></p>
				</div>
				
			</div>

	  	</div>	
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>


<div class="row">

	<div class="span7">


		<h3>Registration</h3>
		<hr>

		<div class="well">

			<%= form_for(@user) do |f| %>

				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :name %>
				<%= f.text_field :name %>

				<%= f.label :birth_date, "Birth date" %>
				<%= f.text_field :birth_date, 'data-behaviour' => 'datepicker' %>

				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :contact %>
				<%= f.text_field :contact %>

				<%= f.label 'Location' %>
				<%= f.collection_select :location_id, Location.order("name"), :id, :name %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirm your password" %>
				<%= f.password_field :password_confirmation %>

				<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

			<% end %>

		</div>

	</div>

	<aside class="span4 offset1">
		
		<div class="well">
			<big><%= link_to "What is Activity finder?", about_path %></big>
		</div>
		
		<div class="well">
			<h4>Registration:</h4>
			<hr>

			<dd>
				<li>create new activities</li>
				<li>join to activities</li>
				<li>add comments to activities</li>
				<li>evaluate sport facilities</li>
				<li>follow people</li>
				<li>read and comment users' posts</li>
				<li>add own post</li>
				<li>see new activities of your followers</li>	
			</dd>
		</div>

	</aside>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<% if @user != current_user %>

	<ul class="nav nav-tabs">
		<li class="active">
			<a href="<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="<%= @user.id %>/activities">Created activities</a>
		</li>

		<li>
			<a href="<%= @user.id %>/participations">Participations</a>
		</li>

		<li>
			<a href="<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>

				<section>
					<p>
						<h4>Created activities:</h4>
		
						<% @my_activities.each do |i| %>

							<a href="<%= activity_path(i) %>">

								<font color="black">
									<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

										<%= i.beg_date %> (<%= time_ago_in_words(i.beg_date) %>)<br>
										<%= i.getParticipantCount %> joined people<br>
										<%= i.getType %><br>
										<%= i.getLocation %>

									</div>
								</font>

							</a>

						<% end %>
		  			</p>
				</section>

			</aside>

			<div class="span6">

				<div style="width: 100%;">
					<div style="float:left; width: 70%">
						<%= render 'shared/stats' %>
					</div>

					<% if signed_in? %>

						<div style="float:right;">
							<% if current_user.followingsCount(@user) == 0 %>
								<%= link_to follow_user_path, :class => 'btn'  do %>
									<i class="icon-heart icon-black"></i> Follow
								<% end %>

							<% else %>
								<%= link_to unfollow_user_path, :class => 'btn'  do %>
									<i class="icon-ban-circle icon-black"></i> Unfollow
								<% end %>
							<% end %>

						</div>

					<% end %>

				</div>
				<div style="clear:both"></div>

				<hr>
				
				<% if signed_in? %>

					<%= form_for Post.new do |f| %>

						<%= render 'shared/error_messages', object: f.object %>
				
						<div class="field">
							<%= f.text_area :content, placeholder: "Write a post" %>
							<%= f.hidden_field :target_id, :value => @user.id %>
						</div>

						<%= f.submit " Add post ", class: "btn btn-small btn-primary" %>

					<% end %>

					<hr>

				<% end %>

				<ol class="posts">
					<%= render @posts %>
				</ol>

			</div>

			<aside class="span3">
				
				<section>
					<div class="well">
						<h4>Favourite activities:</h4>
		
						<% @user.myActivities.each do |i| %>
							<dd>
								<li>
									<%= @user.getType(i.activity_type_id).name %>
								</li>
							</dd>
						<% end %>
		 			 </div>
				</section>

				<section>
					<p>
						<h4>Will participate:</h4>
						
						<% @activities.each do |i| %>

							<a href="<%= activity_path(i) %>">

								<font color="black">
									<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

										<%= i.beg_date %> (<%= time_ago_in_words(i.beg_date) %>)<br>
										<%= i.getParticipantCount %> joined people<br>
										<%= i.getType %><br>
										<%= i.getLocation %>

									</div>
								</font>

							</a>

						<% end %>
						
		  			</p>
				</section>				

				
			</aside>

	  	</div>

<% else %>

	<ul class="nav nav-tabs">
		<li class="active">
			<a href="<%= @user.id %>">General</a>
		</li>

		<li>
			<a href="<%= @user.id %>/info">Profile Info</a>
		</li>

		<li>
			<a href="<%= @user.id %>/following">Following(<%= @user.getFollowedCount %>)</a>
		</li>

		<li>
			<a href="<%= @user.id %>/followers">Followers(<%= @user.getFollowersCount %>)</a>
		</li>
	</ul>

	<div class="row">
			<aside class="span3">
				<section>
					<span>
						<font size="5"><%= link_to @user.name, @user %></font>
					</span>

					<a href="<%= user_path(@user) %>">
						<%= image_tag("/images/person.jpg") %>
					</a>
				</section>


				<section>

					<p>
						<h4>My activities:</h4>
		
						<% @user.getActivities.each do |i| %>

						<a href="<%= activity_path(i) %>">

							<font color="black">
								<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

									<%= time_ago_in_words(i.beg_date) %><br>
									<%= i.getParticipantCount %> joined people<br>
									<%= i.getType %><br>
									<%= i.getLocation %>

								</div>
							</font>

						</a>

					<% end %>

		  			</p>
				</section>
				

			</aside>

			<div class="span6">

				<div style="width: 100%;">
					<div style="float:left; width: 65%">
						<%= render 'shared/stats' %>
					</div>

					<div style="float:right;">
						<%= link_to edit_user_path(current_user), :class => 'btn'  do %>
							<i class="icon-wrench icon-black"></i> Acount settings
						<% end %>
					</div>
				</div>
				<div style="clear:both"></div>

				<hr>

				<%= form_for Post.new do |f| %>

					<%= render 'shared/error_messages', object: f.object %>
				
					<div class="field">
						<%= f.text_area :content, placeholder: "Write a post" %>
						<%= f.hidden_field :target_id, :value => @user.id %>
					</div>

					<%= f.submit " Add post ", class: "btn btn-small btn-primary" %>

				<% end %>

				<hr>

				<ol class="posts">
					<%= render @posts %>
				</ol>

			</div>

			<aside class="span3">
				<section>
					<p>
						<h4>My participations:</h4>
						
						<% @activities.each do |i| %>

						<a href="<%= activity_path(i) %>">

							<font color="black">
								<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

									<%= time_ago_in_words(i.beg_date) %><br>
									<%= i.getParticipantCount %> joined people<br>
									<%= i.getType %><br>
									<%= i.getLocation %>

								</div>
							</font>

						</a>

					<% end %>
						
		  			</p>
				</section>				

			</aside>

	  	</div>	
<% end %>			