config/routes.rb
SampleApp::Application.routes.draw do
  get "participations/new"

	resources :users do
		member do
			get :following, :followers, :info, :deletefavourite, :follow, :unfollow, :participations, :activities
		end
	end

	resources :sessions, only: [:new, :create, :destroy]

	resources :posts, only: [:create, :destroy]
	resources :post_comments, only: [:create, :destroy]

	resources :followings, only: [:create, :destroy]

	resources :activities do
		member do
			get :removeFacility, :join, :cancel, :comment
		end
	end

	resources :participations

	resources :facilities do
    	member do
     		 get :evaluate, :addToActivity, :set, :activities
		end
	end

	resources :activity_comments, only: [:create, :destroy]

	resources :activity_facilities, only: [:create, :destroy]

	resources :evaluations, only: [:create, :destroy]

	root to: 'static_pages#home'

	match '/find_activity', to: 'activities#find', via: :get
	match '/find_activities', to: 'activities#find_activities', via: :get

	match '/find_users', to: 'users#find_users', via: :get	

	match '/create_activity', to: 'activities#new'
	match '/my_activities', to: 'activities#my'

	match '/find_facilities', to: 'facilities#find_facilities', via: :get

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/my_participations', to: 'activities#participations'

	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base

	attr_accessible :user_id, :title, :activity_type_id, :beg_date, :end_date, :beg_time, :end_time, :note, :location_id


	belongs_to :user
	belongs_to :location
	belongs_to :activity_type

	has_many :participations, dependent: :destroy
	has_many :activity_comments, dependent: :destroy
	has_many :activity_facilities, dependent: :destroy


	validates :user_id, presence: true 
	validates :title, presence: true
	validates :beg_date, presence: true
	validates :end_date, presence: true
	validates :note, presence: true, length: { maximum: 1000 }

	def getLocation
		@loc = Location.find(location_id).name
	end

	def getRegion
		@loc = Location.find(location_id).region_id
		@region = Region.find(@loc).name
	end

	def getType
		@type = ActivityType.find(activity_type_id).name
	end

	def getAuthor(author)
		@auth = User.find(author)
	end

	def participantCount(user,activity)
		@participation = Participation.where("user_id = ? AND activity_id = ?", user, activity).count
	end

	def getCommentsCount
		@count = ActivityComment.where("activity_id = ?", id).count
	end

	def getFacilitiesCount
		@count = ActivityFacility.where("activity_id = ?", id).count
	end

	def getFacilities
		@facility = Facility.find(1)
	end

	def getParticipantCount
		@count = Participation.where("activity_id = ?",id).count
	end

	def allActivities
		@act = Activity.find(:all)
	end


end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
	attr_accessible :all

	has_many :activities
	has_many :user_activities
	has_many :activity_type_evaluations

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :signed_in_user, only: [:index, :create, :destroy, :edit, :update, :new, :my, :addFacility, :cancel]
  before_filter :correct_user,   only: [:destroy, :edit, :update]

	def new
		@activity = Activity.new
	end
  
	def show
		@activity= Activity.find(params[:id])
		@participants = User.joins(:participations).where("activity_id = ?", @activity.id).paginate(page: params[:page])
    	@activity_comments = ActivityComment.where("activity_id = ?", @activity.id).order("created_at asc").paginate(page: params[:page])
		@facilities = Facility.joins(:activity_facilities).where("activity_id = ?", @activity.id)
		@activity_comment = @activity_comments.build
		@similiar = Activity.where("location_id = ? AND activity_type_id = ?", @activity.location_id, @activity.activity_type_id)
		@similiar = @similiar.shuffle[0,5]

	end

	def my
		@activities = Activity.where("user_id = ?", current_user.id).order("beg_date asc").paginate(page: params[:page])
		@foll_act = Activity.joins(:user).joins("inner join followings on followings.followed_id = user_id").where("follower_id = ? AND activities.user_id != ?", current_user.id, current_user.id)
		@foll_act = @foll_act.shuffle[0,6]
	end

	def participations
		@activities = Activity.joins(:participations).where("participations.user_id = ? AND beg_date >= ?", current_user.id, Date.today.to_date).order("beg_date asc").paginate(page: params[:page])
		@recommended = Activity.where("location_id = ?", current_user.location_id)
		@recommended = @recommended.shuffle[0,6]
	end

	def join
		if signed_in?
			@activity = Activity.find(params[:id])
			@participation = Participation.new
			@participation.activity_id = params[:id]
			@participation.user_id = current_user.id
			@participation.save!
			redirect_to :action => "show", :id => @activity.id
			flash[:success] = "Successfuly joined!"
		else
			flash[:alert] = "You have to sign in to join this activity!"
			redirect_to signin_path
		end
	end

	def cancel
		@activity = Activity.find(params[:id])
		@participation = Participation.where("user_id = ? AND activity_id = ?", current_user, @activity.id)
		@participation.destroy(@participation.first.id)
		redirect_to :back
			flash[:success] = "Successfuly canceled!"
	end

	def edit
		@activity= Activity.find(params[:id])
	end

	def update

		@activity= Activity.find(params[:id])

		if @activity.update_attributes(params[:activity])
			flash[:success] = "Activity updated"   
			redirect_to @activity
		else
			render 'edit'
		end
	end

	def find
		@recommended = Activity.where("location_id = ?", current_user.location_id)
		@recommended = @recommended.shuffle[0,3]
	end


	def find_activities
		@activities = Activity.where("activity_type_id = ? AND location_id = ? AND beg_date >= ?", params[:activity_type_id], params[:location_id], Date.today.to_date).order("beg_time").paginate(page: params[:page])

		@location = params[:location_id]
		@type = params[:activity_type_id]
	end

	def index
		@activities = Activity.paginate(page: params[:page])
	end

	def create

		@activity = current_user.activities.build(params[:activity])

		@post = Post.new
		@post.user_id = @activity.user_id
		@post.target_id = @activity.user_id 

		if @activity.save
			@post.content = "# " + @activity.id.to_s
			@post.save!
			flash[:success] = "Activity created!"
			redirect_to :action => "show", :id => @activity
		else
			render 'static_pages/home'
		end
	end

	def destroy

		@participation = Participation.where("activity_id = ?", @activity.id)
		@participation.each do |i|
			i.destroy
		end

		@activity.destroy
		redirect_to root_url
	end

	def removeFacility(id)
		@fac = Facility.find(id)
		@fac.destroy
	end

	private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
		@activity = current_user.activities.find_by_id(params[:id])
		redirect_to root_url if @activity.nil?
    end

end

app/views/activities/_activity.html.erb
<a href="<%= activity_path(activity) %>">

	<font color="black">
		<div class="well" style="width:96%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

			<h4>
				<%= time_ago_in_words(activity.beg_date) %>
			</h4>

			<p>

				<div style="width: 100%;">
					<div style="float: left; width: 13%">
						<span class="activity_title">
							<b>Title:</b> 
						</span></br>						
		
						<span class="activity_type_id">
							<b>Type:</b> 
						</span></br>

						<span class="location_id">
							<b>Location:</b>
						</span>
					</div>

					<div style="float: left; width: 37%">
							
						<%= activity.title %></br>

						<span class="activity_type_id">
							<%= activity.getType %>
						</span></br>

						<span class="location_id">
							<%= activity.getLocation %>
						</span>
					</div>

					<div style="float: left; width: 12%">
						<span class="joined">
							<b>Joined:</b>
						</span></br>

						<span class="beg">
							<b>Begin:</b>
						</span></br>
				
						<span class="end">
							<b>End:</b>
						</span>
					</div>

					<div style="float: left;">
						<%= activity.getParticipantCount %> people</br>						
	
						<span class="beg">
							<%= activity.end_date %> at <%= activity.beg_time.strftime('%H:%M') %>
						</span></br>
				
						<span class="end">
							<%= activity.end_date %> at <%= activity.end_time.strftime('%H:%M') %>
						</span>
					</div>
					
				</div>
				<div style="clear:both"></div>

			</p>

		</div>
	</font>
</a>

app/views/activities/edit.html.erb
<% provide(:title, "Edit activity") %> 

<div class="row">
	<div class="span8 offset2">

		<h3>Update your activity</h3>
		<hr>
		
		<div class="well">

			<%= form_for(@activity) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>

				<%= f.label :title %>
				<%= f.text_field :title %>

				<%= f.label :beg_date %>
				<%= f.text_field :beg_date, 'data-behaviour' => 'datepicker' %>

				<%= f.label :end_date %>
				<%= f.text_field :end_date, 'data-behaviour' => 'datepicker' %>

				<%= f.label :beg_time %>
				<%= f.text_field :beg_time %>

				<%= f.label :end_time %>
				<%= f.text_field :end_time %>

				<%= f.label :location_id %>
				<%= f.collection_select :location_id, Location.all, :id, :name %>


				<%= f.label :activity_type_id %>
				<%= f.collection_select :activity_type_id, ActivityType.all, :id, :name %>

				<%= f.label :activity_note %>
				<%= f.text_field :note %>

				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<% end %>

		</div>

	</div>
</div>

app/views/activities/find.html.erb
<% provide(:title, "Find Activity") %>

<div class="row">
	<div class="span8">

		<h3>Find sport activities</h3>

		<hr>

		<div class="well">

			<%= form_tag '/find_activities', method: :get do %>

				<%= label_tag :location_id, 'Location' %>
				<%= collection_select(:location_id, nil , Location.order("name"), :id, :name, :prompt => false) %>
				<br><br>

				<%= label_tag :activity_type_id, 'Activity type' %>
				<%= collection_select(:activity_type_id, nil , ActivityType.all, :id, :name, :prompt => false) %>
				<br><br>			

				<div>
					<%= submit_tag 'Find activity', class: "btn btn-large btn-primary" %>
				</div>

			<% end %>

		</div>

	</div>

	<aside class="span4">

		<section>

			<h4>Try also this activities:</h4>

			<% @recommended.each do |i| %>

					<a href="<%= activity_path(i) %>">

						<font color="black">
							<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">
									
								<%= i.getType %>, <%= i.getLocation %><br>
								<%= i.beg_date %> (<%= time_ago_in_words(i.beg_date) %>)<br>
								<%= i.getParticipantCount %> joined people<br>	

							</div>
						</font>
					</a>

				<% end %>	

		</section>
	</aside>

</div>

app/views/activities/find_activities.html.erb
<% provide(:title, "Find Activities") %>
  
<div class="row">

	<%= form_tag '/find_activities', method: :get do %>

		<div class="well">

			<div style="width: 100%;">
						
				<div style="float: left; width: 43%">
					<%= label_tag :location_id, 'Location' %>
				</div>

				<div style="float: left; width: 43%">
					<%= label_tag :activity_type_id, 'Activity type' %>
				</div>

			</div>
			<div style="clear:both"></div>


			<div style="width: 100%;">
						
				<div style="float: left; width: 43%">
					<%= collection_select(:location_id, nil , Location.order('name'), :id, :name, {:selected => @location}) %>
				</div>

				<div style="float: left; width: 43%">
					<%= collection_select(:activity_type_id, nil , ActivityType.all, :id, :name, {:selected => @type}) %>
				</div>
					
				<div style="float: right;">
					<%= submit_tag '  Search  ', class: "btn btn-large btn-primary" %>
				</div>

			</div>
			<div style="clear:both"></div>

		</div>

	<% end %>

	<h3>Found activities: </h3>

	<hr>

	<% if @activities.count == 0 %>
		<div class="well">
			<big>Sorry, we have no activity for you. You can <%= link_to "create", create_activity_path%> your own activity</big>
		</div>
	<% end %>

	<%= will_paginate(@activities) %>		
		<%= render @activities %>
	<%= will_paginate(@activities) %>

</div>

app/views/activities/my.html.erb
<% provide(:title, 'My activities') %>

<div class="row">

	<aside class="span4">
		<section>

			<div class="well">

			<h4>Followers' activities:</h4>

				<% @foll_act.each do |i| %>

					<a href="<%= activity_path(i) %>">

						<font color="black">
							<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

								<%= time_ago_in_words(i.beg_date) %> (<%= i.beg_date %>)<br>
								<%= i.getParticipantCount %> joined people<br>
								<%= i.getType %><br>
								<%= i.getLocation %>

							</div>
						</font>

					</a>

				<% end %>

			</div>			

		</section>
	</aside>

	<div class="span8">
		<h3>My activities (<%= current_user.getActivityCount %>)</h3>
		  
		<hr>

		<ol class="activities">
			<%= render @activities %>
		</ol>

		<%= will_paginate @activities %>

	</div>
</div>

app/views/activities/new.html.erb
<% provide(:title, 'Create Activity') %>

<div class="row">

	<div class="span10 offset1">

		<h3>Create your own activity</h3>

		<hr>

		<div class="well">

			<%= form_for(@activity) do |f| %>

				<%= render 'shared/error_messages', object: f.object %>

					<%= f.label 'Activity Title'%>
					<%= f.text_field :title %>

					<div style="width: 100%;">
						<div style="float: left; width: 22%">
							<%= f.label 'Begin date'%>
							<%= f.text_field :beg_date, 'data-behaviour' => 'datepicker' %>
						</div>

						<div style="float: left; width: 22%">
							<%= f.label 'Begin time'%>
							<%= f.text_field :beg_time, 'data-behaviour' => 'datetimepicker' %>
						</div>

						<div style="float: right; width: 22%">
							<%= f.label 'End time'%>
							<%= f.text_field :end_time, 'data-behaviour' => 'datetimepicker' %>
						</div>
				
						<div style="float: right; width: 22%">
							<%= f.label 'End date'%>
							<%= f.text_field :end_date, 'data-behaviour' => 'datepicker' %>
						</div>
					
					</div>
					<div style="clear:both"></div>


					<div style="width: 100%;">
						<div style="float: left; width: 46%">
							<%= f.label 'Location' %><%= f.collection_select :location_id, Location.order("name"), :id, :name %>
						</div>

						<div style="float: right; width: 46%">
							<%= f.label :activity_type_id %><%= f.collection_select :activity_type_id, ActivityType.all, :id, :name %>
						</div>
					
					</div>
					<div style="clear:both"></div>

					<%= f.label :activity_note %>
					<%= f.text_field :note %>

				<br><br><%= f.submit "Create Activity", class: "btn btn-large btn-primary" %>

			<% end %>
		</div>
	</div>
</div>

app/views/activities/participations.html.erb
<% provide(:title, 'My participations') %>

<div class="row">
	<aside class="span4">
		<section>

			<div class="well">

				<h4>Recommended activities:</h4>

				<% @recommended.each do |i| %>

					<a href="<%= activity_path(i) %>">

						<font color="black">
							<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

								<%= time_ago_in_words(i.beg_date) %> (<%= i.beg_date %>)<br>
								<%= i.getParticipantCount %> joined people<br>
								<%= i.getType %><br>
								<%= i.getLocation %>

							</div>
						</font>

					</a>

				<% end %>

			</div>
		</section>
	</aside>

	<div class="span8">

		<h3>My participations(<%= @activities.count %>)</h3>
		<hr>

		<%= render @activities %>

		<%= will_paginate @activities %>

	</div>

</div>

app/views/activities/show.html.erb
<% provide(:title, @activity.title) %>

<div class="row">

	<aside class="span3">

		<%= image_tag("/images/activity.jpg", :size => "400x300") %>
	
		<div class="well">

			<section>	
				<h4>Joined people(<%= @activity.getParticipantCount %>):</h4>

				<% @participants.each do |i| %>
					<dd>
						<%= link_to i.name, i %>
					</dd>
				<% end %>
			</section>

		</div>


		<section>	
			<h4>Similiar activities:</h4>

			<% @similiar.each do |i| %>

				<a href="<%= activity_path(i) %>">

					<font color="black">
						<div class="well" style="width:80%;background:#00FFFF" onmouseover="this.style.background='#87CEFA';" onmouseout="this.style.background='#00FFFF';">

							<%= i.beg_date %> (<%= time_ago_in_words(i.beg_date) %>)<br>
							<%= i.getParticipantCount %> joined people<br>
							<%= i.getType %><br>
							<%= i.getLocation %>

						</div>
					</font>

				</a>

			<% end %>
		</section>
		

	</aside>

	<div class="span9">
	
		<span class="title">
			<h3><%= link_to @activity.title, @activity %></h3><br>
		</span>

				
		<% if signed_in? %>

			<div class="btn-group-left">	

				<% if @activity.participantCount(current_user,@activity) == 0 %>
					<%= link_to join_activity_path(@activity.id), :class => 'btn'  do %>
						<i class="icon-ok icon-black"></i> Join this activity
					<% end %>
				<% else %>
					<%= link_to cancel_activity_path(@activity.id), :class => 'btn'  do %>
						<i class="icon-ban-circle icon-black"></i> Cancel participation
					<% end %>
				<% end %>


				<% if current_user?(@activity.user) %>

					<%= link_to edit_activity_path(@activity.id), :class => 'btn'  do %>
						<i class="icon-pencil"></i> Edit this activity
					<% end %>

					<%= link_to @activity, :method => :delete, data: { confirm: "You sure?" } , :class => 'btn'  do %>
						<i class="icon-remove"></i> Delete this activity
					<% end %>

				<% end %>

			</div>

			<br><br>

		<% else %>

			<%= link_to join_activity_path(@activity.id), :class => 'btn'  do %>
				<i class="icon-ok icon-black"></i> Join this activity
			<% end %>

			<br><br>

		<% end %>

		<div class="well">

				<div style="width: 100%;">
					<div style="float:left; width: 25%">
						<b>
							Type:<br>
							Author:<br>
							Location:<br>
							Begin:<br>
							End:<br>
							Note:<br>
						</b>

					</div>
					<div style="float:left;">
						<%= @activity.getType %><br>
						<%= link_to @activity.getAuthor(@activity.user_id).name, @activity.getAuthor(@activity.user_id) %><br>
						<%= @activity.getLocation %><br>
						<%= @activity.beg_date %> at <%= @activity.beg_time.strftime('%H:%M') %><br>
						<%= @activity.end_date %> at <%= @activity.end_time.strftime('%H:%M') %><br>
						<%= @activity.note %><br>

					</div>
	
				</div>
				<div style="clear:both"></div>

			<span class="timestamp">
				<br>Created <%= time_ago_in_words(@activity.created_at) %> ago
				<br>Updated <%= time_ago_in_words(@activity.updated_at) %> ago
	  		</span>

		</div>

		
		<div class="well">

			<h4>Added facilities (<%= @activity.getFacilitiesCount %>)</h4></br>

			<% @facilities.each do |i| %>
				<dd>
					<%= link_to i.title, i %>
				</dd>
			<% end %>

		</div>


		<div class="well">

			<h4>Comments (<%= @activity.getCommentsCount %>)</h4>

			<ol class="activity_comments">
				<%= render @activity_comments %>
			</ol>

			<%= will_paginate @activity_comments %>

		</div>

		<% if signed_in? %>

			<div class="well">

				<%= form_for(@activity_comment) do |f| %>
					<%= render 'shared/error_messages', object: f.object %>
					<%= f.text_area :text, placeholder: "Add comment..." %>
					<%= f.hidden_field :activity_id, :value => @activity.id %>
					<%= f.submit "Add comment", :class => "btn btn-success btn-small"  do %>
						<i class="icon-ban-circle icon-black"></i>
					<% end %>
				
				<% end %>

			</div>

		<% end %>

	</div>

</div>