config/routes.rb
SampleApp::Application.routes.draw do
  get "participations/new"

	resources :users do
		member do
			get :following, :followers, :info, :deletefavourite, :follow, :unfollow, :participations, :activities
		end
	end

	resources :sessions, only: [:new, :create, :destroy]

	resources :posts, only: [:create, :destroy]
	resources :post_comments, only: [:create, :destroy]

	resources :followings, only: [:create, :destroy]

	resources :activities do
		member do
			get :removeFacility, :join, :cancel, :comment
		end
	end

	resources :participations

	resources :facilities do
    	member do
     		 get :evaluate, :addToActivity, :set, :activities
		end
	end

	resources :activity_comments, only: [:create, :destroy]

	resources :activity_facilities, only: [:create, :destroy]

	resources :evaluations, only: [:create, :destroy]

	root to: 'static_pages#home'

	match '/find_activity', to: 'activities#find', via: :get
	match '/find_activities', to: 'activities#find_activities', via: :get

	match '/find_users', to: 'users#find_users', via: :get	

	match '/create_activity', to: 'activities#new'
	match '/my_activities', to: 'activities#my'

	match '/find_facilities', to: 'facilities#find_facilities', via: :get

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/my_participations', to: 'activities#participations'

	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">

	<small>Activity Finder v0.1b © Jozef Zatko</small>

	<nav>
		<ul>
			<li><b><%= link_to "About", about_path %></b></li>
			<li><b><%= link_to "Contact", contact_path %></b></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Activity Finder", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">

		 <li>
			<%= link_to root_path do %>
				<i class="icon-home"></i> Home				
			<% end %>
		</li>

          <% if signed_in? %>
			<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-star"></i> <%= "Activities" %> <b class="caret"></b>
              </a>
			<ul class="dropdown-menu">
                <li>
					<%= link_to find_activity_path do %>
						<i class="icon-search"></i> Find activities
					<% end %>
				</li>

				<li class="divider"></li>
                
				<li>
					<%= link_to create_activity_path do %>
						<i class="icon-plus"></i> Create activity
					<% end %>
				</li>

				<li class="divider"></li>

				<li>
					<%= link_to my_participations_path do %>
						<i class="icon-tags"></i> My participations
					<% end %>
				</li>

				<li class="divider"></li>

				<li>
					<%= link_to my_activities_path do %>
						<i class="icon-star"></i> My activities
					<% end %>
				</li>
				       
              </ul>

               <li>
					<%= link_to facilities_path do %>
						<i class="icon-th"></i> Sport facilities
					<% end %>
				</li>

			<li>
				<%= link_to users_path do %>
					<i class="icon-user"></i> Users
				<% end %>
			</li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-flag"></i> <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
					<%= link_to current_user do %>
						<i class="icon-user"></i> My profile
					<% end %>
				</li>
                <li class="divider"></li>
                <li>
                 <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
			

			<li>
				<%= link_to new_user_path do %>
					<i class="icon-list-alt"></i> Registration
				<% end %>
			</li>

            <li>
				<%= link_to signin_path do %>
					<i class="icon-circle-arrow-right"></i> Sign in
				<% end %>
			</li>


          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activity Finder  <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>